### ISSUE TITLE
CEN +

### ISSUE THREAD

**Issue by Tentalex** [OpenWebNet-HA/MyHOME#105]
Hello,
I have bticino Myhomeserver1 and i integrated it whit HA. I want to use the events in HA to trigger automations. In home + progject I configure 1 button whit scenario cen plus (only wait 1 second). When I press the button in the log of plugin I receive this message:
```
2024-01-29 22:39:39.833 DEBUG (MainThread) [custom_components.myhome] [Myhomeserver1 gateway - 192.168.178.52] Message received: `*25*21#1*22##`
2024-01-29 22:39:39.834 INFO (MainThread) [custom_components.myhome] [Myhomeserver1 gateway - 192.168.178.52] Button 1 of CEN+ object 2 has been pressed
```
So I have configure an automation like this:
```
- id: test_pulsante_bticino
  alias: test_pulsante_bticino
  trigger:
  - platform: event
    event_type: myhome_cenplus_event
    event_data:
      event: pushbutton_short_press
      object: 22 _(2 or 22?? I try both)_
      pushbutton: 1,2
  action:
  - service: notify.alessio
    data:
      title: '*Premuto*'
      message: Premuto
  mode: single
```
unfortunately nothing happens.
Can someone help me.
Thanks
Alessio
