### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by Marko99f** [OpenWebNet-HA/MyHOME#106]
I dont understand how to connect to my f454
![Screenshot 2024-02-03 011130](https://github.com/anotherjulien/MyHOME/assets/158359125/b9249668-2a9c-4bfc-acdf-e05dcddabf4f)

**Comment by f18m** [comment]
hi @Marko99f ,
I'm having your same issue (although in my case I own a MyHomeServer1).
I'm trying to debug the problem by increasing log level. 
My suggestion is for you to do the same, e.g. by adding to your configuration.yaml:

```
logger:
  default: warning
  logs:
    custom_components.myhome: debug
```
