### ISSUE TITLE
My home stopping Update

### ISSUE THREAD

**Issue by manueltn78** [OpenWebNet-HA/MyHOME#135]
Hi, I have Ha that stop updating My home components.
I see powered off lights that are On, anfd if I try to toggle, the button return to off even with the light on....
The only thingI can do to solve is to reload the gateway (In my case a MH201).
Anyone have a solution?
thank you.

**Comment by manueltn78** [comment]
I have an update:
In network switch i noti c'è that every 6-8 minutes the link go off and on.
After this the integration stop working an I have to reload it!

**Comment by zltigo** [comment]
>Ha that stop updating My home components.
Updating also disappears after a few minutes of work.
Rebooting gateway MH200N has no effect. Reloading MyHome integration restores functionality for a short time.
[short.log](https://github.com/user-attachments/files/16646371/short.log)
>Anyone have a solution?
Тhe same question :(

**Comment by riccardilorenzo** [comment]
Same issue here.
I have to reload the integration (at the moment I have an automation that does this every 10 minutes, but it is both dangerous (for automations that may not complete) and annoying).

**Comment by zltigo** [comment]
So far the way out of this state is as follows:
1) shutdown HA
2) reset HM200N
3) wait start HM200N
4) up HA
After this it works for several weeks.
I have an idea for a more convenient automatic option. I'm waiting for a failure to check it.

**Comment by barto28** [comment]
Exact same issue. Plugin is working properly until it doesn't (very short amount of time maybe 10min max).
Clicking on light may turn off/on (depending on current state) successfully for one attempt only. After that only a relaod of the integration make it work again for 10 minutes.

@riccardilorenzo can you share your automation for restarting the integration please ?

**Comment by riccardilorenzo** [comment]
@barto28 here you are.
This fires every 10 minutes in the 15th second (to not interfere with other automations that may launch at X o'clock).
It simply reloads a HA entity of MyHome using the option available also from the GUI. Of course, this makes every HA entity connected to MyHome integration unavailable for a few seconds.

```
- id: '1724433704712'
  alias: Autofix MyHome
  description: 'Reloads config entry for a single HA entity belonging to MyHome.'
  trigger:
  - platform: time_pattern
    seconds: '15'
    minutes: /10
  condition: []
  action:
  - action: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: light.presa_comodino_lorenzo
  mode: single
```
