### ISSUE TITLE
Echec de la configuration

### ISSUE THREAD

**Issue by OZEO-DOOZ** [OpenWebNet-HA/MyHOME#161]
Bonjour,

Je me permets de venir vers vous car j'ai un soucis de configuration sur le module.

J'ai mis la bonne adresse IP que j'ai testé au préalable : 192.168.1.35
Mdr par défaut : 12345

chemin
/config/myhome.yaml

avec le contenu suivant : 
f454:
  mac: '00:03:50:A4:00:F3'
  light:
  switch:
    jardin:
      where: '11'
      name: PC
      dimmable: False
      manufacturer: BTicino
      model: F411U2
<img width="506" alt="Capture d’écran 2025-01-16 115013" src="https://github.com/user-attachments/assets/9b379c22-00d7-41ab-8f53-56ebda628d0a" />
<img width="625" alt="Capture d’écran 2025-01-16 115108" src="https://github.com/user-attachments/assets/15186e62-9e6d-42f3-8b6c-29203007292e" />

Avez vous une idée?
Merci par avance !

**Comment by wave68runner** [comment]
je vois que tu as mis la ref F411U2 au lieu de /2, je ne sais pas si cela a une influence

**Comment by OZEO-DOOZ** [comment]
Les produits que j'ai sont bien des f411u2 , mais il y a aucune différence de fonctionnement avec le f411/2

**Comment by OZEO-DOOZ** [comment]
Bonjour,
J'ai le meme résultat

<img width="314" alt="Image" src="https://github.com/user-attachments/assets/94c2c305-d014-4fc1-acb7-473e73de5e50" />

<img width="416" alt="Image" src="https://github.com/user-attachments/assets/33ccaa4e-3f6f-4adf-85ff-65bec7db7c1a" />

**Comment by OZEO-DOOZ** [comment]
je me demande néanmoins si la différence de chemin sur le fichier n'aurait pas un impact? Si je marque autre chose, il ne semble pas voir le fichier mais cette diférence m'interroge.

**Comment by cyrilcordoba** [comment]
Bonjour

Il me semble que j'avais le même problème initialement. Avez vous essayé de configurer en light plutôt qu'en switch ou adapter la configuration switch avec les même paramètres que ci dessous ?
```
# Device configuration
f454:
  mac: "00:03:50:a4:yy:xx"
  light:
    entreespots:
      where: "11"
      name: Entree Spots
      dimmable: False
      manufacturer: Legrand
      model: F411
  switch:
    gestioneauballonecs:
      where: "61"
      name: Ballon ECS
      class: outlet
      manufacturer: Legrand
      model: F411
```
