### ISSUE TITLE
Problems loading lights after 2022.8

### ISSUE THREAD

**Issue by teejay-87** [OpenWebNet-HA/MyHOME#59]
Hello,

Since update to 2022.8, MyHome integration has problem loading any `light` (appliances configured as `switch` works fine, interestingly).
Lights do not load on HA startup, but they do if I reload the integration from the Settings panel.

There is a log about deprecated methods:
```Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77 
First occurred: 23 agosto 2022, 00:43:56 (3 occurrences) 
Last logged: 23 agosto 2022, 00:43:56

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for myhome using this method at custom_components/myhome/__init__.py, line 89: device_registry = await hass.helpers.device_registry.async_get_registry()
Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for myhome using this method at custom_components/myhome/__init__.py, line 159: entity_registry = await hass.helpers.entity_registry.async_get_registry()
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for myhome using this method at custom_components/myhome/__init__.py, line 160: device_registry = await hass.helpers.device_registry.async_get_registry()```

**Comment by teejay-87** [comment]
Updating my installation to use `master` branch, the log about deprecation disappeared, but the problem remains, albeit symptoms changed.

In particular, at HA starts, lights appear (instead of not being present at all) but do not function.
This at least prevent them from being removed from HomeKit devices every time I restart HA.
Then, reloading the integration makes them work fine.

I workarounded the problem by using this automation:
```alias: Reload MyHome when Home Assistant starts
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
  - service: homeassistant.reload_config_entry
    data:
      entry_id: <my_home_entity_id>
mode: single```

**Comment by viperxeno** [comment]
I have the same error after update HA to 2022.8.0. need for fix bug

**Comment by caiosweet** [comment]
> I have the same error after update HA to 2022.8.0. need for fix bug

Read here. [why the integration fails to load correctly. ](https://community.home-assistant.io/t/legrand-bticino-myhome/229337/755?u=caiosweet)

**Comment by caiosweet** [comment]
> Updating my installation to use `master` branch, the log about deprecation disappeared, but the problem remains, albeit symptoms changed.
> 
> In particular, at HA starts, lights appear (instead of not being present at all) but do not function. This at least prevent them from being removed from HomeKit devices every time I restart HA. Then, reloading the integration makes them work fine.
> 
> I workarounded the problem by using this automation:
> 
> ```
> alias: Reload myHome when Home Assistant starts
> description: ""
> trigger:
>   - platform: homeassistant
>     event: start
> condition: []
> action:
>   - delay:
>       hours: 0
>       minutes: 0
>       seconds: 10
>       milliseconds: 0
>   - service: homeassistant.reload_config_entry
>     data:
>       entry_id: <my_home_entity_id>
> mode: single
> ```

little correction. if you use entity, entity_id should be used and not entry_id. :)

`entity_id: <my_home_entity_id>`

**Comment by alessandro-lac** [comment]
I tried both automation @caiosweet and the one linked in the community, but it looks like they do not properly work. I also tried to increase the delay or even run the automation twice. Still, some entities are not working after a restart. If I reload it manually, everything works fine.
```alias: Reload MyHome at Start
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 30
      milliseconds: 0
  - service: hassio.addon_stdin
    data:
      addon: myhome
      input: reload
mode: single
```
Any suggestion?

**Comment by viperxeno** [comment]
> I tried both automation @caiosweet and the one linked in the community, but it looks like they do not properly work. I also tried to increase the delay or even run the automation twice. Still, some entities are not working after a restart. If I reload it manually, everything works fine.
> 
> ```
> description: ""
> trigger:
>   - platform: homeassistant
>     event: start
> condition: []
> action:
>   - delay:
>       hours: 0
>       minutes: 1
>       seconds: 30
>       milliseconds: 0
>   - service: hassio.addon_stdin
>     data:
>       addon: myhome
>       input: reload
> mode: single
> ```
> 
> Any suggestion?

I have same problem... it need reload manually

**Comment by caiosweet** [comment]
> > I tried both automation @caiosweet and the one linked in the community, but it looks like they do not properly work. I also tried to increase the delay or even run the automation twice. Still, some entities are not working after a restart. If I reload it manually, everything works fine.
> > ```
> > description: ""
> > trigger:
> >   - platform: homeassistant
> >     event: start
> > condition: []
> > action:
> >   - delay:
> >       hours: 0
> >       minutes: 1
> >       seconds: 30
> >       milliseconds: 0
> >   - service: hassio.addon_stdin
> >     data:
> >       addon: myhome
> >       input: reload
> > mode: single
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any suggestion?
> 
> I have same problem... it need reload manually


A suggestion is to check if any entity is unavailable at startup.
`states('binary_sensor.pir_sala') in ['unavailable', 'unknown'] `

This is my test automation, **to be refined**, where in addition I have also added the thermostat status request, so as not to wait for the central unit to send the request too late (usually every 15 minutes)

```
automation:
  - alias: "Timer Richiesta Energia"
    initial_state: true
    max_exceeded: silent
    trigger:
      - platform: homeassistant
        event: start
        id: "avvio"
      - platform: time_pattern
        hours: "/2"
    variables:
      tot_zone: 4
    action:
      - choose:
          - conditions: "{{ states('sensor.temp_quadro')|int(0)<= 0 or 
              states('binary_sensor.pir_sala') in ['unavailable', 'unknown'] }}" 
            sequence:
              - service: homeassistant.reload_config_entry
                data:
                  entity_id: light.luce_bagno
                  # area_id: 
                  # device_id:
                  # entry_id: c25758ebba2003c3586f9b8d92558fce

      - service: myhome.start_sending_instant_power
        data:
          duration: 125
          entity_id: sensor.consumo_generale_power
      - delay:
          milliseconds: 500
      - service: myhome.sync_time
        data: {}
      - delay:
          milliseconds: 500
      - service: myhome.send_message
        data:
          message: "*#1*0##" # All Status

      - choose:
          - conditions: "{{ 'avvio' in trigger.id }}"
            sequence:
              - alias: Repeat the sequence UNTIL the conditions are true
                repeat:
                  sequence:
                    - delay:
                        seconds: 2
                    - service: myhome.send_message
                      data:
                        message: "*4*311*#{{repeat.index}}##" #richiesta stato probe n
                  until:
                    - condition: template
                      value_template: "{{ repeat.index == tot_zone }}"
```

**Comment by caiosweet** [comment]
> ```
>   - service: hassio.addon_stdin
>     data:
>       addon: myhome
>       input: reload
> ```

I don't think this is the right way. it is not an addon but an integration.
The right way is to use  `homeassistant.reload_config_entry`

```
              - service: homeassistant.reload_config_entry
                data:
                  entity_id: light.luce_bagno # any myhome entity in your system
                  # area_id: 
                  # device_id:
                  # entry_id: c25758ebba2003c3586f9b8d92558fce # or your entry_id in your system

```
