### ISSUE TITLE
Status indications are wrong

### ISSUE THREAD

**Issue by Depechie** [OpenWebNet-HA/MyHOME#61]
Ever since Home Assistant 2022.9.0 things have become worse. Problem is, I know this is due to the changes of Home Assistant internally and not the MyHome integration but it still sucks :/

So since 2022.9 I have a lot off out of sync status notifications.
Meaning lights that are turned off are still seen as turned on by the MyHome integration.

Is there any way to get back a more reliable status?

**Comment by Depechie** [comment]
So it seems that the addon keeps getting an old state and shows that. Any action ( turning on / off lights ) still work but the state of all the lights is stale and does not change.
Until I restart Home Assistant and then everything is fine again for a few hours ( how long I do not know because I only notice it when automations are not working ).

**Comment by Depechie** [comment]
As a test I installed Home Assistant Core in docker on 2 different raspberry pi's and those are working almost perfectly.
Totally no idea why my supervised install on my Intel NUC keeps messing up with MyHome.
I even deleted the integration and re-added it.
On the NUC I'm of course running way more extra add ons ( like HomeKit ), not sure if those could interfere ...

**Comment by rodegt** [comment]
Ho lo stesso problema anche io, stato delle luci non aggiornato!!! Cosa si fa quindi?

**Comment by stepir** [comment]
it's the event session crashed - confirm reloading the integration solve your issue, then you need to setup an automation  like the following (you need to replace with an entity that is always available)

```
alias: Reload MHome
description: ""
trigger:
  - platform: time_pattern
    hours: /4
condition: []
action:
  - service: homeassistant.reload_config_entry
    target:
      entity_id:
        - climate.central_unit
    data: {}
  - service: homeassistant.reload_config_entry
    target:
      entity_id:
        - binary_sensor.yale_smart_alarm_battery
    data: {}
mode: single
```
