### ISSUE TITLE
Bticino F520

### ISSUE THREAD

**Issue by hexesoft-stefano-rossi** [OpenWebNet-HA/MyHOME#68]
I connected 15 elements of the F520 to my Home assistant. 
All right for the following information Energy, Energy (current month), Energy (doday)
While for power I don't get any information.
I need to read the instantaneous electricity consumption
you can help me ? 
thank you

**Comment by sxpert** [comment]
You need to tell the system to start to send the power information. This is done on purpose so as to not overload the bus.
If you really have lots of power measurement devices, you may have to split the bus and use a second gateway.

I use this: 

```yaml
alias: Start getting Instant power Data
description: ""
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /2
condition: []
action:
  - service: myhome.start_sending_instant_power
    data:
      duration: 125
      entity_id: sensor.eau_chaude_sanitaire_eau_chaude_sanitaire_power_2
  - service: myhome.start_sending_instant_power
    data:
      entity_id: sensor.baie_reseau_bureau_baie_reseau_bureau_power_2
      duration: 125
  - service: myhome.start_sending_instant_power
    data:
      entity_id: sensor.baie_switches_sejour_baie_switches_sejour_power_2
      duration: 125
mode: single
```
