### ISSUE TITLE
Binary sensor not reachable

### ISSUE THREAD

**Issue by FOSV** [OpenWebNet-HA/MyHOME#71]
Hi, I have a door sensor (dry contact) connected with Bticino 3477 interface which from the configuration appears to have the following attributes:

**Area=1    ||    A=1    ||    PL=1**

So I configured it as a binary sensor with the following yaml lines:

```
  - platform: myhome
    devices:
      contatto_porta:
        where: '31'
        name: Contatto Porta
        class: door
        manufacturer: BTicino
        model: 3477
```

**At the moment, however, I get the following error from the log:**

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.myhome
Source: custom_components/myhome/gateway.py:323
Integration: MyHome (documentation, issues)
First occurred: 16:49:58 (1 occurrences)
Last logged: 16:49:58

Could not send message *#25*31##.
```

**And the following error every time the door sensor changes state due to an opening or closing:**

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.myhome
Source: custom_components/myhome/gateway.py:119
Integration: MyHome (documentation, issues)
First occurred: 16:50:00 (3 occurrences)
Last logged: 17:10:00

Data received is not a message: None
```
I specify that home assistant shows me the entity as available but does not detect the status, or rather, always reveals it as closed.
I am sure the clean contact is working properly because when opening the door (via MyHome automation) it turns on a light.
@anotherjulien Could you kindly tell me what I'm doing wrong?
Thanks in advance!
