### ISSUE TITLE
Error setting up entry MH200N Gateway for myhome

### ISSUE THREAD

**Issue by 4tViert** [OpenWebNet-HA/MyHOME#86]
Hello, 
pretty new here so I hope someone can help. 
I have installed this repository almost 2 years ago without any problems, but since last week I cannot connect to my gateway anymore. 
Before I had all coding in the config.yaml and after checking I have reated a new file according to wiki named myhome.yaml and changed the syntax. 
But I cannot connect. There are 2 errors:

Error doing job: Tas exception was never retrieved and Error setting up entry MH200N Gateway for myhome

No idea how to solve. Do i need to set a reference in config.yaml or any other things to adapt?
![grafik](https://github.com/anotherjulien/MyHOME/assets/78379459/7ae9b879-6990-4a90-9142-0deb046867f5)

Thx.

Brg

**Comment by caiosweet** [comment]
Have you tried uninstalling the component, restarting and installing again. It may happen that outdated configurations remain.
Did you set the gateway in the configuration with the mac address?
For example as per [wiki general-structure](https://github.com/anotherjulien/MyHOME/wiki/Configuration#general-structure):
```

mh202n:
   mac: "00:00:50:11:B8:55"

   binary_sensor:
     pir_xxx:
       where: "331"
       name: Pir xxx
       class: motion
       manufacturer: BTicino
       model: N4640
     pir_yyy:
       where: "371"
       name: Pir yyy
       class: motion
       manufacturer: BTicino
       model: NT4610

   covers:
     cover_studio:
     ...

```
